# Copyright 2019 DLR - GSOC
# SPDX-License-Identifier: Apache-2.0

name: Maven build

on:
  push:
    paths:
    - 'src/**'
    - 'pom.xml'
    - '.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache local Maven repository
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: Build result
        path: target
